### ISSUE TITLE
Only show items on first page of report that has list that spans multiple pages?

### ISSUE THREAD

**Issue by willjohnson** [thinreports/thinreports-generator#48]
Is there a way to only show items on the first page of a report that includes a list that spans multiple pages. E.g. I have an introductory paragraph for the list but it doesn't need to be on each page--only the first.

I was thinking that maybe it could be included in the list header and then I could not display the header on pages 2 and on but can't figure that out. I also don't know how to test what page number the report is on.

**Comment by hidakatsuya** [comment]
@willjohnson 

> Is there a way to only show items on the first page of a report that includes a list that spans multiple pages.

There is no easy way for it. However, you may be able to try the following way:

 * Use two templates
 * The one is for first page, the another one is for second page or later
 * The both includes list which have same layout and id
 * The list of the another one is disable auto page-break
 * The one includes items that only show on first page

```ruby
# Note: This code is untested.

report = Thinreports::Report.new

report.start_new_page layout: 'first_page_layout.tlf' do |first_page|
  first_page.item(:foo).value = 'bar'
end

row_data.each do |data|
  if report.page_count == 1 && report.list.overflow?
    report.start_new_page layout: 'another_layout.tlf'
  end

  report.list.add_row do |row|
    row.item(:hoge).value = data.hoge
  end
end
```

At the same, we are planning the following feature in order to be able to more easily implement this case.
https://github.com/thinreports/thinreports/issues/7 (in japanese)

**Comment by hidakatsuya** [comment]
@willjohnson Please ask a question in [Google Group](https://groups.google.com/forum/?hl=ja#!forum/thinreports) from next time.

**Comment by willjohnson** [comment]
@hidakatsuya Thank you so much!

That new feature sounds great (based on the Google translation). It should solve my issue of the excess whitespace between elements I was having when the first element was a list that ended up short and the next element was set halfway down the page.

I will ask questions in the Google Group next time. Thanks again.
